### ISSUE TITLE
Projection query with operator

### ISSUE THREAD

**Issue by user1702** [fresheneesz/mongo-parse#1]
I am trying to parse the below mongodb query. It is not giving proper response
db.records.find( { "user_id": { $lt: 42 } }, { "history": 0 } )

var mongoQuery = [{ "user_id": { $lt: 42 } }, { "history": 0 }]
var queryObject = parser.parse(mongoQuery)

Operator field is not coming in the response
{"parts":[{"field":"0","operand":{"user_id":{"$lt":42}},"parts":[]},{"field":"1","operand":{"history":0},"parts":[]}]}

**Comment by fresheneesz** [comment]
Ah, so it looks you're attempting to parse both the query and the projection.  `mongo-parse` only parses the query. So the following should give you a correct response:

```
parser.parse({ "user_id": { $lt: 42 }})
```

Tho I'm not sure if that's what you're looking for. What are you trying to do?

I'll add an example to make it clearer how this is meant to be used.

**Comment by fresheneesz** [comment]
@user1702 I added a small example, does that help?

**Comment by fresheneesz** [comment]
Closing since this is old and isn't a bug with mongo-parse.
