### ISSUE TITLE
Unhandled Rejection: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jgpacheco** [fresheneesz/mongo-parse#10]
Hey guys.
First things first: Good job, this library is really useful.

I'm trying to use `queryObject.matches(document, validate)` function with a document that is deeply nested so I'm passing false as a second argument to avoid the `Unhandled Rejection: RangeError: Maximum call stack size exceeded` error when a deeply nested document is validated. But one of the parts of my query use the `$elemMatch` and the `matches` function is called but without taking in account the value set for `validate` parameter: https://github.com/fresheneesz/mongo-parse/blob/master/matches.js#L156

Same should happen using the `$not` operator: https://github.com/fresheneesz/mongo-parse/blob/master/matches.js#L127

I will build a small PR addressing this issue.

**Comment by fresheneesz** [comment]
Thanks! Glad you like it! If you think people should use it, a star would be appreciated ; )

The pull request looks good! I've pulled it in and published v2.0.3. Thanks again!
