### ISSUE TITLE
Implement Map Keys / Columns

### ISSUE THREAD

**Issue by surjikal** [fresheneesz/mongo-parse#16]
I'd absolutely love to see a function that lets me replace the "columns" or "keys" in a query.

For example, if I have `{$and:[{name:"surjikal"}]}`, I'd like to run something like this:

```javascript
const query = {$and:[{name:"surjikal"}]};
const mapped = MongoParse.parse(query).mapKeys(key => `prefix__${key}`);
```

Where `mapped` is:  ` {$and:[{prefix__name:"surjikal"}]}`

**Comment by fresheneesz** [comment]
You should be able to do that with the `map` method of a parsedQuery object like this:

```javascript
const query = {$and:[{name:"surjikal"}]};
const mapped = MongoParse.parse(query).map((key, value) => {
  let result = {}  
  result[`prefix__${key}`] = value
  return result
);
```

Let me know if that doesn't work (don't have time to test it right now).

**Comment by surjikal** [comment]
Cool thanks!
