### ISSUE TITLE
$in operator not matching for arrays

### ISSUE THREAD

**Issue by platdesign** [fresheneesz/mongo-parse#4]
Hey, nice work!

I tried to match a collection of docs having a schema like:

```javascript
{
	_id:123,
	tags: ['a','b','c']
}
```

... with following query:

```javascript
{
	tags: { $in:['a','b'] }
}
```

... but got no results.

The mongoDB-Docs of `$in` say:

> If the field holds an array, then the $in operator selects the documents whose field holds an array that contains at least one element that matches a value in the specified array [...].

Looked at your implementation and found, that it only can match 'single' values.

```javascript
// matches.js
$in:function(docVal,operand) {
	return operand.indexOf(docVal) !== -1
}
```

Suggestion for an implementation of the mongoDB behavior:

```javascript
$in:function(docVal,operand) {
	if(Array.isArray(docVal)) {
		return docVal.some(function(val) {
			return operand.indexOf(val) !== -1;
		});
	} else {
		return operand.indexOf(docVal) !== -1
	}
}
```

**Comment by fresheneesz** [comment]
Thanks! Mind creating a pull request for that? A unit test would be nice too.

**Comment by fresheneesz** [comment]
Thanks for the pull request! Did you have any trouble running the unit tests?

**Comment by fresheneesz** [comment]
1.0.6 is in npm with this and a $nin fix as well
